import { FaDatabase, FaNodeJs } from "react-icons/fa";
import { DiNodejs, DiMysql, DiGit, DiCss3 } from "react-icons/di";
import colorSharp from "../assets/img/color-sharp.png";

export const Skills = () => {
  return (
    <section>
      <section className="skill" id="skills">
        <div className="container">
          <div className="row">
            <div className="col-12">
              <div className="skill-bx wow zoomIn">
                <h2>SKILLS </h2>
                <div className="skills-container">
                  <div className="big_screen">
                    <table className="skills-table-top">
                      <thead className="skills-table text-center">
                        <tr>
                          <th>
                            <a
                              href="https://www.w3.org/html/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
                                alt="html5"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Html</div>
                          </th>
                          <th>
                            <a
                              href="https://nodejs.org"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
                                alt="nodejs"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Node.js</div>
                          </th>
                          <th>
                            <a
                              href="https://www.sql.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Sql_data_base_with_logo.png/200px-Sql_data_base_with_logo.png"
                                alt="SQL"
                                width="100"
                                height="100"
                              />
                            </a>
                          </th>
                          <th>
                            <a
                              href="https://www.mysql.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
                                alt="mysql"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>MySQL</div>
                          </th>
                          <th>
                            <a
                              href="https://www.python.org"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
                                alt="python"
                                width="40"
                                height="40"
                              />{" "}
                            </a>{" "}
                            <div>Python</div>
                          </th>
                          <th>
                            <a
                              href="https://git-scm.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/git/git-original.svg"
                                alt="Git"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Git</div>
                          </th>
                          <th>
                            <a
                              href="https://www.cprogramming.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg"
                                alt="c"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>C</div>
                          </th>
                        </tr>
                      </thead>
                    </table>
                    <table className="skills-table ">
                      <thead className="skills-table text-center">
                        <tr>
                          <th>
                            <a
                              href="https://reactjs.org/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
                                alt="react"
                                width="40"
                                height="40"
                              />{" "}
                            </a>{" "}
                          </th>
                          <th>
                            <a
                              href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
                                alt="javascript"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>JavaScript</div>
                          </th>
                          <th>
                            <a
                              href="https://aws.amazon.com"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
                                alt="aws"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>AWS</div>
                          </th>
                          <th>
                            <a
                              href="https://www.w3schools.com/css/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
                                alt="css3"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>CSS3</div>
                          </th>
                          <th>
                            <a
                              href="https://nextjs.org/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original-wordmark.svg"
                                alt="Next.js"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Next</div>
                          </th>
                          <th>
                            <a
                              href="https://www.mongodb.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
                                alt="mongodb"
                                width="40"
                                height="40"
                              />
                            </a>
                          </th>
                          <th>
                            <a
                              href="https://expressjs.com"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
                                alt="express"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Express</div>
                          </th>
                          <td>
                            <a
                              href="https://tailwindcss.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-plain.svg"
                                alt="Tailwind CSS"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Tailwind CSS</div>
                          </td>
                        </tr>
                      </thead>
                    </table>
                  </div>
                  <div className="small_screen">
                    <table className="skills-table-top">
                      <thead className="skills-table text-center">
                        <tr>
                          <th>
                            <a
                              href="https://www.w3.org/html/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg"
                                alt="html5"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Html</div>
                          </th>
                          <th>
                            <a
                              href="https://nodejs.org"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original-wordmark.svg"
                                alt="nodejs"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Node.js</div>
                          </th>
                          <th>
                            <a
                              href="https://www.sql.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Sql_data_base_with_logo.png/200px-Sql_data_base_with_logo.png"
                                alt="SQL"
                                width="100"
                                height="100"
                              />
                            </a>
                          </th>
                          <th>
                            <a
                              href="https://www.mysql.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original-wordmark.svg"
                                alt="mysql"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>MySQL</div>
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td>
                            <a
                              href="https://www.w3schools.com/css/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original-wordmark.svg"
                                alt="css3"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>CSS3</div>
                          </td>
                          <td>
                            <a
                              href="https://git-scm.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/git/git-original.svg"
                                alt="Git"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Git</div>
                          </td>
                          <td>
                            <a
                              href="https://developer.mozilla.org/en-US/docs/Web/JavaScript"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg"
                                alt="javascript"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>JavaScript</div>
                          </td>
                          <td>
                            <a
                              href="https://aws.amazon.com"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/amazonwebservices/amazonwebservices-original-wordmark.svg"
                                alt="aws"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>AWS</div>
                          </td>
                        </tr>
                      </tbody>
                    </table>

                    <table className="skills-table">
                      <thead className="skills-table text-center">
                        <tr>
                          <th>
                            <a
                              href="https://www.python.org"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/python/python-original.svg"
                                alt="python"
                                width="40"
                                height="40"
                              />{" "}
                            </a>{" "}
                            <div>Python</div>
                          </th>
                          <th>
                            <a
                              href="https://reactjs.org/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/react/react-original-wordmark.svg"
                                alt="react"
                                width="40"
                                height="40"
                              />{" "}
                            </a>{" "}
                          </th>
                          <th>
                            <a
                              href="https://nextjs.org/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/nextjs/nextjs-original-wordmark.svg"
                                alt="Next.js"
                                width="40"
                                height="40"
                              />
                            </a>
                            <div>Next</div>
                          </th>
                          <th>
                            <a
                              href="https://www.mongodb.com/"
                              target="_blank"
                              rel="noreferrer"
                            >
                              {" "}
                              <img
                                src="https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original-wordmark.svg"
                                alt="mongodb"
                                width="40"
                                height="40"
                              />
                            </a>
                          </th>
                        </tr>
                      </thead>
                      <tbody>
                        <td>
                          <a
                            href="https://www.cprogramming.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <img
                              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/c/c-original.svg"
                              alt="c"
                              width="40"
                              height="40"
                            />
                          </a>
                          <div>C</div>
                        </td>{" "}
                        <td>
                          <a
                            href="https://expressjs.com"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <img
                              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original-wordmark.svg"
                              alt="express"
                              width="40"
                              height="40"
                            />
                          </a>
                          <div>Express</div>
                        </td>
                        <td>
                          <a
                            href="https://tailwindcss.com/"
                            target="_blank"
                            rel="noreferrer"
                          >
                            <img
                              src="https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-plain.svg"
                              alt="Tailwind CSS"
                              width="40"
                              height="40"
                            />
                          </a>
                          <div>Tailwind CSS</div>
                        </td>
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <img className="background-image-left" src={colorSharp} alt="Image" />
      </section>
    </section>
  );
};
